services:
    Aws\S3\S3Client:
        arguments:
            - version: '2006-03-01'
              region: 'us-east-1'
              credentials:
                  key: '%env(AWS_S3_ACCESS_ID)%'
                  secret: '%env(AWS_S3_ACCESS_SECRET)%'


# config/packages/flysystem.yaml
# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        local.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/images'

        # maybe this will allow thumbs on s3: https://stackoverflow.com/questions/78046249/liip-imagine-generate-wrong-cache-url-with-aws-s3-liip-imagine-vich-uploader
        default.storage:
            adapter: 'aws'
            visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                streamReads: true
                prefix: '%env(S3_STORAGE_PREFIX)%'

when@dev:
    flysystem:
        storages:
            default.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/data/omar'

