pwa:
    image_processor: 'pwa.image_processor.imagick'
    favicons:
        enabled: false
        src: "images/todo.png"
        tile_color: "#c026d3"
        background_color: "#c3d7f7"
        image_scale: 66
        border_radius: 50
        low_resolution: true
        safari_pinned_tab_color: "#c3d7f7"
        use_silhouette: true

    manifest:
        enabled: true
#        public_url: '/pwa/site.{locale}.webmanifest'
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'SUEÑO ALETEANDO'
        short_name: 'ALETEANDO'
        description: 'Omar Medina artista visual especializado en laca y cultura chiapaneca nos presenta una exposición basada en el uso de madera, piedra y barro como parte de su inspiración y armonía, dando paso a la creación de figuras y texturas azarosas e improvisada'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: ./
#        start_url: "app.start_url"
        icons:
            - src: "images/todo.png"
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              image_scale: 90
              purpose: 'any'
            - src: "images/todo.png"
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              background_color: "#c3d7f7"
              image_scale: 50
              border_radius: 25
              purpose: 'maskable'

            - src: 'images/audio-guide-music-svgrepo-com.svg'
              sizes: any
            # https://www.veryicon.com/icons/miscellaneous/smart-site/noise-3.html
#            - src: "/images/pulse-svgrepo-com.svg"
##              sizes: [32, 48, 72, 96, 120, 128, 144, 180, 192, 256, 384, 512]
##            - src: "images/space-planet-icon.svg"

        screenshots:
            - "images/screenshot1.png"
            - "images/screenshot2.png"
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            resource_caches:
                - match_callback: 'origin: cdn.jsdelivr.net'
                  strategy: 'CacheOnly'
                  preload_urls: # Optional, but you are now sure the library is preloaded even if used on another page the user never met before
#                - cache_name: app_pages
#                  match_callback: '/planet\/\d+/'
#                  strategy: StaleWhileRevalidate # 'CacheOnly' # ??
#                  broadcast: true
#                  broadcast_headers:
#                  preload_urls:
#                      - 'app_landing'

#            offline_fallback:
#                page: 'app_offline_page'
